name: Package

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        clean: false
        repository: 'GoogleCloudPlatform/DataflowTemplates'
        path: 'DataflowTemplates'
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install Neo4j Dataflow Template
      run: mvn -V -B install --file DataflowTemplates/pom.xml -am -pl v2/googlecloud-to-neo4j -DskipTests -Djib.skip
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
